/**
 * Runtime Environment Configuration
 *
 * IMPORTANT: This file is generated at runtime by docker-entrypoint.sh
 * Do NOT edit this file manually. It will be overwritten.
 *
 * Sets window._env_ with environment variables from the Docker container:
 * - VITE_API_BASE_URL: Backend API base URL
 * - VITE_ADMIN_USERS: Comma-separated admin usernames
 * - VITE_DELETE_PERMISSION_USERS: Users with delete permissions
 * - etc.
 */

// This is a placeholder - the actual content is generated at runtime
window._env_ = {
  VITE_API_BASE_URL: 'http://localhost:8080/api'
};

